# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('asistentes', models.ManyToManyField(to='usuario.Usuario')),
                ('experimentos', models.ManyToManyField(to='experimento.Experimento')),
            ],
        ),
    ]
