# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_orden', models.DateField(blank=True, default=datetime.datetime.now)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='solicitud.Solicitud')),
            ],
        ),
    ]
