# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('cientifico', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
