# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=40, null=True)),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now)),
                ('asistente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistente', to='usuario.Usuario')),
                ('cientifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cientifico', to='usuario.Usuario')),
            ],
        ),
    ]
