# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20170323_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
