# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clasificacion', models.CharField(default='Sin clasificación', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=5000)),
                ('version', models.FloatField(default=1.0)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='protocolo.ClasificacionProtocolo')),
                ('insumos', models.ManyToManyField(related_name='insumos', to='insumo.Insumo')),
            ],
        ),
    ]
