# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('experimentos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experimento.Experimento')),
            ],
        ),
    ]
