# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
        ('protocolo', '0002_remove_protocolo_experimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='insumos',
            field=models.ManyToManyField(null=True, to='insumo.Insumo'),
        ),
    ]
