# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0003_protocolo_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='insumos',
            field=models.ManyToManyField(to='insumo.Insumo'),
        ),
    ]
