# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0004_auto_20170323_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='protocolo',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
