# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0005_auto_20170326_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Protocolo'),
        ),
    ]
