# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
        ('protocolo', '0006_paso_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='insumos',
        ),
        migrations.AddField(
            model_name='paso',
            name='entradas',
            field=models.ManyToManyField(related_name='entradas', to='insumo.Insumo'),
        ),
        migrations.AddField(
            model_name='paso',
            name='salidas',
            field=models.ManyToManyField(related_name='salidas', to='insumo.Insumo'),
        ),
    ]
