# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0007_auto_20170326_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='pasos',
            field=models.ManyToManyField(related_name='pasos', to='protocolo.Paso'),
        ),
    ]
