# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0008_protocolo_pasos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paso',
            name='protocolo',
        ),
    ]
