# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0009_remove_paso_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='clasificacion',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
