# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0011_clasificacionprotocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacionprotocolo',
            old_name='clasificacion',
            new_name='nombre_clasificacion',
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='protocolo.ClasificacionProtocolo'),
        ),
    ]
