# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0012_auto_20170326_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='codigo',
            field=models.CharField(default=b'PRO-000', max_length=10),
        ),
    ]
