# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0013_protocolo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
