# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_auto_20170326_2017'),
        ('protocolo', '0017_auto_20170326_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paso',
            name='entradas',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='pasos',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='insumos',
            field=models.ManyToManyField(related_name='insumos', to='insumo.Insumo'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.DeleteModel(
            name='Paso',
        ),
    ]
