# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0018_auto_20170326_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
