# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='fecha_resultado',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
