# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resultado', '0001_initial'),
        ('insumo', '0001_initial'),
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('insumos', models.ManyToManyField(to='insumo.Insumo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.Maquina')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado.Resultado')),
            ],
        ),
    ]
