# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocolo', '0001_initial'),
        ('insumo', '0001_initial'),
        ('maquina', '0001_initial'),
        ('experimento', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento', to='experimento.Experimento')),
                ('insumos', models.ManyToManyField(related_name='insumos_m', to='insumo.Insumo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='maquina.Maquina')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolo', to='protocolo.Protocolo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyecto.Proyecto')),
            ],
        ),
    ]
